apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
      #this is directly base imaging taking from docker nginx
        #image: nginx:1.14.2
        #this is docker file uploaded on docker
        image: mannakod/pullthiskube
        ports:
        - containerPort: 80
